name: Voice Create Bot Publish
on:
  push:
    branches:
      - develop
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.semvers.outputs.patch }} # set the app_version to be the PATCH updated version
      tag: ${{ steps.semvers.outputs.v_patch }} # set the tag to be the PATCH updated version.
    env:
      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
    - uses: actions/checkout@v3.0.2
      with:
        fetch-depth: 0
    # Get the current tag
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.1.0 # Optional fallback tag to use when no tag can be found
    # calculate the next version
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - run: echo "app_version ${{ steps.semvers.outputs.patch }}"
  docker:
    runs-on: ubuntu-latest
    needs: version
    # env:
    #   DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
    steps:
    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE="camalot/voice-create-bot-docker";
        GHCR_IMAGE="ghcr.io/camalot/voice-create-bot-docker";

        TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${{ needs.version.outputs.app_version }},${GHCR_IMAGE}:latest,${GHCR_IMAGE}:${{ needs.version.outputs.app_version }}";
        echo ::set-output name=tags::${TAGS}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push DockerHub and GHCR
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        build-args: |
          PROJECT_NAME=voice-create-bot-docker
          BUILD_VERSION=${{ needs.version.outputs.app_version }}
        tags: ${{ steps.prep.outputs.tags }}
  merge:
    runs-on: ubuntu-latest
    needs:
    - docker
    - version
    steps:

    - uses: actions/checkout@v3.0.2
    - name: Merge develop -> master
      uses: devmasx/merge-branch@1.4.0
      with:
        type: now
        from_branch: develop
        target_branch: master
        github_token: ${{ github.token }}
    # https://github.com/marketplace/actions/create-tag
    - name: Create Tag
      uses: negz/create-tag@v1
      with:
        version: ${{ needs.version.outputs.tag }}
        message: ''
        token: ${{ github.token }}
    # - name: Create Release
    #   uses: softprops/action-gh-release@v1
    #   if: startsWith(github.ref, 'refs/tags/')
    #   env:
    #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    #   with:
    #     body_path: CHANGELOG.txt
    #     name: "${{ needs.version.outputs.app_version }}"
